### ISSUE TITLE
The code fails in demo example

### ISSUE THREAD

**Issue by waniz** [brannondorsey/midi-rnn#3]
this code doesn't work in Ubuntu and Win10

`def parse_midi(path):`
`    midi = None`
    `with open(path, 'r') as f:`
       ` try:`
            `midi = pretty_midi.PrettyMIDI(f)`
            `midi.remove_invalid_notes()`
        `except:`
          ` pass`
  `  return midi`

Midi files encoded not in UTF-8

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 13: invalid continuation byte`

**Comment by brannondorsey** [comment]
Should now be fixed with https://github.com/brannondorsey/midi-rnn/pull/5.
